rules:
  bad-dl: true
  class-members: true
  data-prop: true
  deprecation-note: true
  description: true
  heading: true
  lint: false
  spec-alignment: true
  structure-consistency: true
  syntax-section: true
