rules:
  bad-dl: false
  class-members: false
  data-prop: false
  deprecation-note: false
  description: false
  heading: true
  lint: false
  spec-alignment: false
  structure-consistency: true
  syntax-section: false
