rules:
  anchor-links: true
  bad-dl: true
  class-members: true
  data-prop: true
  deprecation-note: true
  description: true
  heading: true
  lint: false
  see-also: true
  spec-alignment: true
  structure-consistency: true
  syntax-section: false
