rules:
  bad-dl: false
  class-members: false
  data-prop: false
  deprecation-note: false
  description: false
  heading: false
  lint: false
  spec-alignment: false
  structure-consistency: false
  syntax-section: true
