rules:
  anchor-links: false
  bad-dl: false
  class-members: false
  data-prop: false
  deprecation-note: false
  description: false
  heading: false
  lint: false
  macro-style: false
  see-also: false
  spec-alignment: false
  structure-consistency: true
  syntax-section: false
